version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  # valheim-server:
  #   image: lloesche/valheim-server
  #   container_name: valheim-server
  #   cap_add:
  #     - sys_nice
  #   stop_grace_period: 120s
  #   ports:
  #     - "2456-2457:2456-2457/udp"
  #   volumes:
  #     - ${VALHEIM_DATA_DIR}:/opt/valheim
  #     - ${VALHEIM_CONFIG_DIR}:/config
  #   environment:
  #     SERVER_NAME: "${VALHEIM_SERVER_NAME}"
  #     WORLD_NAME: "${VALHEIM_WORLD_NAME}"
  #     SERVER_PASS: "${VALHEIM_SERVER_PASS}"

  # minecraft-server:
  #   image: itzg/minecraft-server
  #   ports:
  #     - 25565:25565
  #   environment:
  #     EULA: "TRUE"
  #     TYPE: "${MINECRAFT_TYPE}"
  #     VERSION: "${MINECRAFT_VERSION}"
  #     SERVER_NAME: "${MINECRAFT_SERVER_NAME}"
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
  #   volumes:
  #     - ${MINECRAFT_DATA_DIR}:/data

volumes:
  postgres:
