name: Deploy

on:
  push:
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Windows 10 Machine
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd Documents\GitHub\gshub\api 
            pm2 stop api 
            rmdir /s /q out 
            git pull 
            npm install 
            npm run build 
            pm2 start api
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          pass: ${{ secrets.REMOTE_PASSWORD }}
